/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cashregister;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.filechooser.FileView;
import javax.swing.text.Document;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.Color;
import javax.swing.LookAndFeel;

/**
 *
 * @author DYICT
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {

        initComponents();
        
        
        DefaultListModel<String> productModel = new DefaultListModel<>();
        productModel.addElement("Apple");
        productModel.addElement("Banana");
        productModel.addElement("Orange");
        productModel.addElement("Milk");
        productModel.addElement("Bread");
        productsList.setModel(productModel);

        cart.setModel(cartModel);
        prices.setModel(pricesModel);
        Rprices.setModel(pricesModel);
        Ritems.setModel(cartModel);
        successReciept.setVisible(false);
        cOut.setVisible(false);
        pMethodLBL.setVisible(false);
        reconsiderAmt.setVisible(false);
        
        
        pricesModel.toArray();
        com.formdev.flatlaf.themes.FlatMacDarkLaf.setup();
        
        
       
        
        
        

        // ImageIcon i = new ImageIcon(getClass().getResource("/com/mycompany/cashregister/shop.png"));
        // photoFrame.setFrameIcon(i);
    }
    DefaultListModel<String> cartModel = new DefaultListModel<>();
    DefaultListModel<String> pricesModel = new DefaultListModel<>();

    public void isLoggedIn(){
    
    
    
    
    }
    public void Balancer() {

        if (Integer.parseInt(outstandingCal.getText()) < 0) {
            padFrame.setVisible(false);
            pMethodLBL.setVisible(true);
            cOut.setVisible(true);
            reconsiderAmt.setVisible(true);
            outstandingCal.setText("0");
        }

    }

    public void Reset() {

        cartModel.clear();
        pricesModel.clear();
        cost.setText("0");
        outstandingCal.setText("0");
        amountCal.setText("0");
        itemsCount.setText("0 Items");
        this.reconsider();

    }

    public void reconsider() {

        padFrame.setVisible(true);
        pMethodLBL.setVisible(false);
        cOut.setVisible(false);
        reconsiderAmt.setVisible(false);
        outstandingCal.setText(cost.getText());
        amountCal.setText("0");
    }

    public void exportFrameToPNG(JInternalFrame frame, String filename) {
        try {
            frame.setVisible(true);
            frame.revalidate();
            frame.repaint();

            int w = frame.getWidth();
            int h = frame.getHeight();

            if (w <= 0 || h <= 0) {
                JOptionPane.showMessageDialog(null, "Frame size is invalid. Cannot export.");
                return;
            }

            BufferedImage image = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
            Graphics2D g2 = image.createGraphics();
            frame.paint(g2);
            g2.dispose();

            ImageIO.write(image, "png", new File(filename));
            JOptionPane.showMessageDialog(null, "PNG saved to: " + filename);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Failed to save PNG.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame2 = new javax.swing.JFrame();
        Reciept = new javax.swing.JPopupMenu();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        successReciept = new javax.swing.JInternalFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        Ritems = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        Rprices = new javax.swing.JList<>();
        Rtotal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        orderNo = new javax.swing.JLabel();
        change = new javax.swing.JLabel();
        RmethodPayment = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        productsList = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jInternalFrame4 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        cost = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        itemsCount = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cart = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        prices = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        cOut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        amountCal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        outstandingCal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        reconsiderAmt = new javax.swing.JButton();
        padFrame = new javax.swing.JInternalFrame();
        one = new javax.swing.JButton();
        four = new javax.swing.JButton();
        two = new javax.swing.JButton();
        five = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        three = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        six = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        backspace = new javax.swing.JButton();
        pMethodLBL = new javax.swing.JLabel();
        chooseMethod = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales Genius");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        setForeground(new java.awt.Color(51, 51, 0));
        setIconImages(null);
        setName("homeFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1613, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1613, 800));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1648, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );

        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.setBackground(new java.awt.Color(153, 204, 255));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(2000, 800));

        successReciept.setBackground(new java.awt.Color(255, 255, 255));
        successReciept.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        successReciept.setClosable(true);
        successReciept.setTitle("Sale Successful!");
        successReciept.setToolTipText("Successful!");
        successReciept.setVisible(true);
        successReciept.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                successRecieptInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        Ritems.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Ritems.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(Ritems);

        Rprices.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Rprices.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(Rprices);

        Rtotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Rtotal.setText("0,00");

        jLabel10.setText("Items");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Price(R)");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Order :");

        jLabel13.setText("Sales Genius");

        jLabel14.setText("+27 81 386 XXXX");

        jLabel15.setText("Thank You For Shopping With Us, Have An Amazing Day!");

        orderNo.setText("0");

        change.setText("Your Change is R0,00");

        RmethodPayment.setText("none");

        time.setText("Time:00:00");

        javax.swing.GroupLayout successRecieptLayout = new javax.swing.GroupLayout(successReciept.getContentPane());
        successReciept.getContentPane().setLayout(successRecieptLayout);
        successRecieptLayout.setHorizontalGroup(
            successRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(successRecieptLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(successRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(successRecieptLayout.createSequentialGroup()
                        .addGroup(successRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(83, 83, 83)
                        .addGroup(successRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rtotal)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(successRecieptLayout.createSequentialGroup()
                        .addGroup(successRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RmethodPayment)
                            .addComponent(change))
                        .addGap(23, 23, 23)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(successRecieptLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(successRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(successRecieptLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(successRecieptLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(orderNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(49, 49, 49))
                    .addGroup(successRecieptLayout.createSequentialGroup()
                        .addGroup(successRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(time)
                            .addComponent(jLabel15))
                        .addGap(0, 45, Short.MAX_VALUE))))
        );
        successRecieptLayout.setVerticalGroup(
            successRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(successRecieptLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(successRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(orderNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(3, 3, 3)
                .addComponent(time)
                .addGap(18, 18, 18)
                .addGroup(successRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(successRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Rtotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(change)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RmethodPayment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(28, 28, 28))
        );

        jInternalFrame2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jInternalFrame2.setVisible(true);

        productsList.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        productsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Logo", "Poster", "Flyer", "Banner" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        productsList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                productsListFocusGained(evt);
            }
        });
        productsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                productsListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(productsList);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Products");

        jInternalFrame4.setBorder(null);
        jInternalFrame4.setVisible(true);

        jLabel2.setText("Total Cost");

        cost.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cost.setText("0");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("R");

        itemsCount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemsCount.setText("0 Items");

        javax.swing.GroupLayout jInternalFrame4Layout = new javax.swing.GroupLayout(jInternalFrame4.getContentPane());
        jInternalFrame4.getContentPane().setLayout(jInternalFrame4Layout);
        jInternalFrame4Layout.setHorizontalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                        .addComponent(cost)
                        .addGap(53, 53, 53)
                        .addComponent(itemsCount))
                    .addComponent(jLabel2))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jInternalFrame4Layout.setVerticalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cost)
                        .addComponent(itemsCount)))
                .addGap(48, 48, 48))
        );

        cart.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cart.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        cart.setToolTipText("Cart");
        cart.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                cartValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(cart);

        prices.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        prices.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        prices.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(prices);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Cart");

        cOut.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cOut.setText("Check Out");
        cOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cOutActionPerformed(evt);
            }
        });

        jLabel3.setText("Amount Being Paid ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("R");

        amountCal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        amountCal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amountCal.setText("0");
        amountCal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Outstanding Amount");

        outstandingCal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        outstandingCal.setForeground(new java.awt.Color(255, 51, 0));
        outstandingCal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outstandingCal.setText("0");
        outstandingCal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        outstandingCal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("R");

        reconsiderAmt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reconsiderAmt.setForeground(new java.awt.Color(0, 153, 255));
        reconsiderAmt.setText("ReEnter Amount");
        reconsiderAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reconsiderAmtActionPerformed(evt);
            }
        });

        padFrame.setVisible(true);

        one.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        one.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                oneKeyPressed(evt);
            }
        });

        four.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        two.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        five.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        five.setText("5");
        five.setToolTipText("");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        seven.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        eight.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        three.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        three.setText("3");
        three.setToolTipText("");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        zero.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        six.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        nine.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        backspace.setBackground(new java.awt.Color(255, 255, 0));
        backspace.setText("Back");
        backspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout padFrameLayout = new javax.swing.GroupLayout(padFrame.getContentPane());
        padFrame.getContentPane().setLayout(padFrameLayout);
        padFrameLayout.setHorizontalGroup(
            padFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(padFrameLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(padFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(zero)
                    .addGroup(padFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(padFrameLayout.createSequentialGroup()
                            .addComponent(seven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(padFrameLayout.createSequentialGroup()
                            .addGroup(padFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(one, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(four, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(padFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(padFrameLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(five, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(padFrameLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(two, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGroup(padFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(padFrameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(padFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(six, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(three, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, padFrameLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        padFrameLayout.setVerticalGroup(
            padFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(padFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(padFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(one)
                    .addComponent(two)
                    .addComponent(three, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(padFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(four, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(five, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(six))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(padFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nine)
                    .addComponent(eight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(padFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(zero, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(backspace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pMethodLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pMethodLBL.setText("Choose Payment Method");

        chooseMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash Payment", "Card Payment" }));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\DYICT\\Documents\\NetBeansProjects\\CashRegister\\src\\main\\java\\com\\mycompany\\cashregister\\Sales.gif")); // NOI18N
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jDesktopPane1.setLayer(successReciept, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jInternalFrame2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jInternalFrame4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cOut, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(amountCal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(outstandingCal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(reconsiderAmt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(padFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(pMethodLBL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(chooseMethod, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInternalFrame4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(cOut))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(amountCal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(jLabel7)
                                .addGap(6, 6, 6)
                                .addComponent(outstandingCal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(reconsiderAmt))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(padFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(pMethodLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(chooseMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(97, 97, 97)
                        .addComponent(successReciept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(452, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel5)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jInternalFrame4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(16, 16, 16)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(amountCal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(outstandingCal))))
                                        .addGap(16, 16, 16)
                                        .addComponent(reconsiderAmt)
                                        .addGap(6, 6, 6)
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(padFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                .addGap(255, 255, 255)
                                                .addComponent(pMethodLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(4, 4, 4)
                                        .addComponent(chooseMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(successReciept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addComponent(cOut))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel6)))))
                .addContainerGap(260, Short.MAX_VALUE))
        );

        jScrollPane6.setViewportView(jDesktopPane1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formComponentShown

    private void backspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceActionPerformed
        // TODO add your handling code here:
        this.Balancer();
        outstandingCal.setText(String.valueOf(Integer.parseInt(outstandingCal.getText()) + Integer.parseInt(amountCal.getText())));
        String text = amountCal.getText();
        if (text.length() > 1) {

            text = text.substring(0, text.length() - 1);

        } else {
            text = "0";
        }
        amountCal.setText(text);
    }//GEN-LAST:event_backspaceActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        // TODO add your handling code here:
        if (amountCal.getText() == "0") {
            amountCal.setText("9");

        } else if (amountCal.getText() != "0") {

            amountCal.setText((String.valueOf(amountCal.getText()) + 9));

        }

        outstandingCal.setText(String.valueOf(Integer.parseInt(cost.getText()) - Integer.parseInt(amountCal.getText())));
        this.Balancer();
    }//GEN-LAST:event_nineActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        // TODO add your handling code here:
        if (amountCal.getText() == "0") {
            amountCal.setText("6");

        } else if (amountCal.getText() != "0") {

            amountCal.setText((String.valueOf(amountCal.getText()) + 6));

        }

        outstandingCal.setText(String.valueOf(Integer.parseInt(cost.getText()) - Integer.parseInt(amountCal.getText())));
        this.Balancer();
    }//GEN-LAST:event_sixActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        // TODO add your handling code here:
        if (amountCal.getText() == "0") {
            amountCal.setText("0");

        } else if (amountCal.getText() != "0") {

            amountCal.setText((String.valueOf(amountCal.getText()) + 0));

        }

        outstandingCal.setText(String.valueOf(Integer.parseInt(cost.getText()) - Integer.parseInt(amountCal.getText())));
        this.Balancer();
    }//GEN-LAST:event_zeroActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        // TODO add your handling code here:
        if (amountCal.getText() == "0") {
            amountCal.setText("3");

        } else if (amountCal.getText() != "0") {

            amountCal.setText((String.valueOf(amountCal.getText()) + 3));

        }

        outstandingCal.setText(String.valueOf(Integer.parseInt(cost.getText()) - Integer.parseInt(amountCal.getText())));
        this.Balancer();
    }//GEN-LAST:event_threeActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        // TODO add your handling code here:
        if (amountCal.getText() == "0") {
            amountCal.setText("8");

        } else if (amountCal.getText() != "0") {

            amountCal.setText((String.valueOf(amountCal.getText()) + 8));

        }

        outstandingCal.setText(String.valueOf(Integer.parseInt(cost.getText()) - Integer.parseInt(amountCal.getText())));
        this.Balancer();
    }//GEN-LAST:event_eightActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        // TODO add your handling code here:
        if (amountCal.getText() == "0") {
            amountCal.setText("7");

        } else if (amountCal.getText() != "0") {

            amountCal.setText((String.valueOf(amountCal.getText()) + 7));

        }

        outstandingCal.setText(String.valueOf(Integer.parseInt(cost.getText()) - Integer.parseInt(amountCal.getText())));
        this.Balancer();
    }//GEN-LAST:event_sevenActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        // TODO add your handling code here:
        if (amountCal.getText() == "0") {
            amountCal.setText("5");

        } else if (amountCal.getText() != "0") {

            amountCal.setText((String.valueOf(amountCal.getText()) + 5));

        }

        outstandingCal.setText(String.valueOf(Integer.parseInt(cost.getText()) - Integer.parseInt(amountCal.getText())));
        this.Balancer();
    }//GEN-LAST:event_fiveActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:

        if (amountCal.getText() == "0") {
            amountCal.setText("2");

        } else if (amountCal.getText() != "0") {

            amountCal.setText((String.valueOf(amountCal.getText()) + 2));

        }

        outstandingCal.setText(String.valueOf(Integer.parseInt(cost.getText()) - Integer.parseInt(amountCal.getText())));
        this.Balancer();
    }//GEN-LAST:event_twoActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        // TODO add your handling code here:
        if (amountCal.getText() == "0") {
            amountCal.setText("4");

        } else if (amountCal.getText() != "0") {

            amountCal.setText((String.valueOf(amountCal.getText()) + 4));

        }

        outstandingCal.setText(String.valueOf(Integer.parseInt(cost.getText()) - Integer.parseInt(amountCal.getText())));
        this.Balancer();
    }//GEN-LAST:event_fourActionPerformed

    private void oneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oneKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneKeyPressed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        // TODO add your handling code here:

        if (amountCal.getText() == "0") {
            amountCal.setText("1");

        } else if (amountCal.getText() != "0") {

            amountCal.setText((String.valueOf(amountCal.getText()) + 1));

        }

        outstandingCal.setText(String.valueOf(Integer.parseInt(cost.getText()) - Integer.parseInt(amountCal.getText())));
        this.Balancer();

    }//GEN-LAST:event_oneActionPerformed

    private void reconsiderAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reconsiderAmtActionPerformed
        // TODO add your handling code here:
        this.reconsider();
    }//GEN-LAST:event_reconsiderAmtActionPerformed

    private void cOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cOutActionPerformed
        // TODO add your handling code here:
        orderNo.setText(String.valueOf(Integer.parseInt(orderNo.getText()) + 1));
        successReciept.setVisible(true);
        successReciept.revalidate();     // Ensure layout is updated
        successReciept.repaint();
        Rtotal.setText("R"+cost.getText()+",00");
        change.setText("Your Change Is R" + String.valueOf((Integer.parseInt(amountCal.getText()) - Integer.parseInt(cost.getText()))));
        RmethodPayment.setText("Payment Method: " + chooseMethod.getSelectedItem());
        this.reconsider();

        LocalTime now = LocalTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
        String formatted = now.format(formatter);
        time.setText("Time: " + formatted);
        Timer exportDelay = new Timer(100, e -> {
            exportFrameToPNG(successReciept, "C:/Users/DYICT/Pictures/Saved Pictures/Reciept" + orderNo.getText() + System.currentTimeMillis() + ".png");
        });
        exportDelay.setRepeats(false);
        exportDelay.start();

        Timer timer = new Timer(500000, e -> successReciept.setVisible(false));
        timer.setRepeats(false);
        timer.start();

        timer.addActionListener(e -> this.Reset());

    }//GEN-LAST:event_cOutActionPerformed

    private void cartValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_cartValueChanged
        // TODO add your handling code here:

        if (!evt.getValueIsAdjusting()) {
            String selected = cart.getSelectedValue();

            if (selected == null) {
                return;
            }

            switch (selected) {
                case "Apple":

                pricesModel.removeElementAt(cartModel.indexOf(selected));

                cartModel.removeElementAt(cartModel.indexOf(selected));

                cost.setText(String.valueOf(Integer.parseInt(cost.getText()) - 3));

                break;
                case "Banana":

                pricesModel.removeElementAt(cartModel.indexOf(selected));
                cartModel.removeElement(selected);

                cost.setText(String.valueOf(Integer.parseInt(cost.getText()) - 4));

                break;
                case "Orange":

                pricesModel.removeElementAt(cartModel.indexOf(selected));
                cartModel.removeElement(selected);

                cost.setText(String.valueOf(Integer.parseInt(cost.getText()) - 5));

                break;
                case "Milk":

                pricesModel.removeElementAt(cartModel.indexOf(selected));
                cartModel.removeElement(selected);

                cost.setText(String.valueOf(Integer.parseInt(cost.getText()) - 18));

                break;
                case "Bread":

                pricesModel.removeElementAt(cartModel.indexOf(selected));
                cartModel.removeElement(selected);

                cost.setText(String.valueOf(Integer.parseInt(cost.getText()) - 22));

                break;
            }

            outstandingCal.setText(cost.getText());
            itemsCount.setText(cartModel.getSize() + " Items");

        }

    }//GEN-LAST:event_cartValueChanged

    private void productsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_productsListValueChanged
        // TODO add your handling code here:

        if (!evt.getValueIsAdjusting()) {
            outstandingCal.setText(String.valueOf(Integer.parseInt(outstandingCal.getText()) - Integer.parseInt(amountCal.getText())));
            String selected = productsList.getSelectedValue();
            if (selected != null) {
                cartModel.addElement(selected);
                if (selected.equals("Apple")) {
                    cost.setText(String.valueOf(Integer.parseInt(cost.getText()) + 3));
                    pricesModel.addElement("R 3,00");

                }
                if (selected.equals("Banana")) {
                    cost.setText(String.valueOf(Integer.parseInt(cost.getText()) + 4));
                    pricesModel.addElement("R 4,00");

                }
                if (selected.equals("Orange")) {
                    cost.setText(String.valueOf(Integer.parseInt(cost.getText()) + 5));
                    pricesModel.addElement("R 5,00");

                }
                if (selected.equals("Milk")) {
                    cost.setText(String.valueOf(Integer.parseInt(cost.getText()) + 18));
                    pricesModel.addElement("R 18,00");

                }
                if (selected.equals("Bread")) {
                    cost.setText(String.valueOf(Integer.parseInt(cost.getText()) + 22));
                    pricesModel.addElement("R 22,00");

                }
                outstandingCal.setText(cost.getText());
                productsList.clearSelection();
                itemsCount.setText(cartModel.getSize() + " Items");

            }
        }

    }//GEN-LAST:event_productsListValueChanged

    private void productsListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productsListFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_productsListFocusGained

    private void successRecieptInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_successRecieptInternalFrameClosed
        // TODO add your handling code here:
        cartModel.clear();
        pricesModel.clear();
        cost.setText("0");
        outstandingCal.setText("0");
        amountCal.setText("0");
        itemsCount.setText("0 Items");
        this.reconsider();
    }//GEN-LAST:event_successRecieptInternalFrameClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaf Cupertino Light look and feel */

      
      

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      /*  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Cupertino Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPopupMenu Reciept;
    public javax.swing.JList<String> Ritems;
    public javax.swing.JLabel RmethodPayment;
    public javax.swing.JList<String> Rprices;
    public javax.swing.JLabel Rtotal;
    public javax.swing.JLabel amountCal;
    public javax.swing.JButton backspace;
    public javax.swing.JButton cOut;
    public javax.swing.JList<String> cart;
    public javax.swing.JLabel change;
    public javax.swing.JComboBox<String> chooseMethod;
    public javax.swing.JLabel cost;
    public javax.swing.JButton eight;
    public javax.swing.JButton five;
    public javax.swing.JButton four;
    public javax.swing.JLabel itemsCount;
    public javax.swing.JDesktopPane jDesktopPane1;
    public javax.swing.JFrame jFrame2;
    public javax.swing.JInternalFrame jInternalFrame1;
    public javax.swing.JInternalFrame jInternalFrame2;
    public javax.swing.JInternalFrame jInternalFrame4;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JLayeredPane jLayeredPane1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JButton nine;
    public javax.swing.JButton one;
    public javax.swing.JLabel orderNo;
    public javax.swing.JLabel outstandingCal;
    public javax.swing.JLabel pMethodLBL;
    public javax.swing.JInternalFrame padFrame;
    public javax.swing.JList<String> prices;
    public javax.swing.JList<String> productsList;
    public javax.swing.JButton reconsiderAmt;
    public javax.swing.JButton seven;
    public javax.swing.JButton six;
    public javax.swing.JInternalFrame successReciept;
    public javax.swing.JButton three;
    public javax.swing.JLabel time;
    public javax.swing.JButton two;
    public javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
